プルリクエストを作成
YUKI-bot19/TODOLIST pull request #1
Opened 2020-11-03 07:23 UTC by YUKI-bot19

レビューお願いします。

2020-11-03 13:50 UTC, myzktkyk requested changes
何点か指摘をしております 🙏

2020-11-03 13:50 UTC, myzktkyk commented on js/main.js
> +  const contents = document.getElementById('text');
`contents` が利用されている個所が無いようです…

2020-11-03 13:50 UTC, myzktkyk commented on js/main.js
> +    const result = items.map((item, i) => {
ここで利用すべきなのは `map` ではなく `forEach` かなと思います。
```suggestion
    items.forEach((item, i) => {
```

2020-11-03 13:50 UTC, myzktkyk commented on js/main.js
> +    items.push(newArr);
ちょっと冗長に感じたので、以下のようにしてはいかがでしょうか？
```suggestion
    items.push({
      id: items,
      comment: taskValue.value,
    });
```

2020-11-03 13:50 UTC, myzktkyk commented on js/main.js
> +  const showArray = items => {
確かに `配列を表示` するんですが…名前が実装に寄りすぎている気がします。
例えば `showTasks` 等はいかがでしょうか？
```suggestion
  const showTasks = items => {
```

2020-11-05 00:23 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください！

2020-11-05 00:23 UTC, kouki-iwahara commented on js/main.js
> +
余計な空行が多いようですので削除しましょう。
基本的に全て詰めて記述して良いです。

2020-11-05 00:23 UTC, kouki-iwahara commented on js/main.js
>    const items = [];
itemというのは抽象的ですので、todosのような具体的な命名にしましょう。

2020-11-05 00:23 UTC, kouki-iwahara commented on js/main.js
> +    items.forEach((item, i) => {
命名に一文字はNGとされていますので避けましょう。
略すなら`idx`とかですね。

2020-11-05 00:23 UTC, kouki-iwahara commented on js/main.js
>        id: items,
idというプロパティに配列itemsを持たせていますが間違い無いですか？

2020-11-06 05:25 UTC, merged